-- =====================================================================
-- REIMI platform — full setup for a NEW project (run once)
-- Generated by scripts/gen-supabase-sql.mjs. Paste into Supabase → SQL Editor → Run.
-- =====================================================================
BEGIN;

-- ---------- migration 0000_init ----------
CREATE TABLE "admin_sessions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"admin_id" uuid NOT NULL,
	"token_hash" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"ip" text,
	"user_agent" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "admin_sessions_token_hash_unique" UNIQUE("token_hash")
);

CREATE TABLE "admin_users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" text NOT NULL,
	"name" text NOT NULL,
	"role" text DEFAULT 'admin' NOT NULL,
	"permissions" text[] DEFAULT '{}' NOT NULL,
	"timezone" text DEFAULT 'Asia/Tokyo' NOT NULL,
	"timezone_mode" text DEFAULT 'auto' NOT NULL,
	"locale" text DEFAULT 'ja' NOT NULL,
	"password_hash" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"last_login_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "admin_users_email_unique" UNIQUE("email")
);

CREATE TABLE "audit_logs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"actor_type" text NOT NULL,
	"actor_id" uuid,
	"actor_label" text,
	"action" text NOT NULL,
	"entity_type" text,
	"entity_id" text,
	"diff" jsonb,
	"ip" text,
	"user_agent" text,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "conversations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" uuid,
	"reservation_id" uuid,
	"category" text NOT NULL,
	"status" text DEFAULT 'received' NOT NULL,
	"assignee_id" uuid,
	"last_message_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "customers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" text NOT NULL,
	"given_name" text NOT NULL,
	"family_name" text NOT NULL,
	"phone" text,
	"country" text,
	"preferred_locale" text DEFAULT 'ja' NOT NULL,
	"tags" text[] DEFAULT '{}' NOT NULL,
	"marketing_opt_in" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "customers_email_unique" UNIQUE("email")
);

CREATE TABLE "guest_access_passes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"reservation_id" uuid NOT NULL,
	"token_hash" "bytea" NOT NULL,
	"valid_from" timestamp with time zone NOT NULL,
	"valid_until" timestamp with time zone NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"verify_method" text DEFAULT 'surname' NOT NULL,
	"created_by" uuid,
	"sent_at" timestamp with time zone,
	"last_used_at" timestamp with time zone,
	"revoked_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "lock_credentials" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"lock_device_id" uuid NOT NULL,
	"reservation_id" uuid NOT NULL,
	"provider_credential_id" text,
	"pin_code" text NOT NULL,
	"valid_from" timestamp with time zone NOT NULL,
	"valid_until" timestamp with time zone NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "lock_devices" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"property_id" uuid NOT NULL,
	"provider" text NOT NULL,
	"external_id" text NOT NULL,
	"name" jsonb NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"battery_level" integer,
	"last_seen_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "messages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"conversation_id" uuid NOT NULL,
	"sender_type" text NOT NULL,
	"sender_id" uuid,
	"body" text NOT NULL,
	"attachments" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "payments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"reservation_id" uuid,
	"kind" text NOT NULL,
	"stripe_payment_intent_id" text,
	"amount" integer NOT NULL,
	"amount_captured" integer DEFAULT 0 NOT NULL,
	"amount_refunded" integer DEFAULT 0 NOT NULL,
	"status" text NOT NULL,
	"qr_code_id" uuid,
	"captured_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "payments_stripe_payment_intent_id_unique" UNIQUE("stripe_payment_intent_id")
);

CREATE TABLE "pricing_rules" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"scope" text NOT NULL,
	"target_id" uuid NOT NULL,
	"name" text NOT NULL,
	"rule_type" text NOT NULL,
	"condition" jsonb NOT NULL,
	"adjust_type" text NOT NULL,
	"adjust_value" integer NOT NULL,
	"priority" integer DEFAULT 100 NOT NULL,
	"stackable" boolean DEFAULT true NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "properties" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"slug" text NOT NULL,
	"business" text NOT NULL,
	"name" jsonb NOT NULL,
	"area" jsonb,
	"summary" jsonb,
	"description" jsonb,
	"timezone" text DEFAULT 'Asia/Tokyo' NOT NULL,
	"check_in_time" text DEFAULT '15:00' NOT NULL,
	"check_out_time" text DEFAULT '11:00' NOT NULL,
	"cleaning_fee" integer DEFAULT 0 NOT NULL,
	"wifi_ssid" text,
	"wifi_password" text,
	"status" text DEFAULT 'draft' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "properties_slug_unique" UNIQUE("slug")
);

CREATE TABLE "qr_codes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"property_id" uuid,
	"purpose" text NOT NULL,
	"slug" text NOT NULL,
	"target_url" text NOT NULL,
	"label" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "qr_codes_slug_unique" UNIQUE("slug")
);

CREATE TABLE "qr_scans" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"qr_code_id" uuid NOT NULL,
	"user_agent" text,
	"ip_hash" text,
	"scanned_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "rate_plans" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"unit_id" uuid NOT NULL,
	"code" text NOT NULL,
	"name" jsonb NOT NULL,
	"base_price" integer NOT NULL,
	"min_nights" integer DEFAULT 1 NOT NULL,
	"max_guests" integer NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "reservations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"code" text NOT NULL,
	"kind" text NOT NULL,
	"property_id" uuid NOT NULL,
	"unit_id" uuid,
	"rate_plan_id" uuid,
	"customer_id" uuid NOT NULL,
	"check_in" date,
	"check_out" date,
	"starts_at" timestamp with time zone,
	"ends_at" timestamp with time zone,
	"adults" integer DEFAULT 1 NOT NULL,
	"children" integer DEFAULT 0 NOT NULL,
	"status" text NOT NULL,
	"price_snapshot" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"total_amount" integer DEFAULT 0 NOT NULL,
	"currency" text DEFAULT 'JPY' NOT NULL,
	"source" text DEFAULT 'direct' NOT NULL,
	"utm_source" text,
	"utm_campaign" text,
	"locale" text DEFAULT 'ja' NOT NULL,
	"hold_expires_at" timestamp with time zone,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "reservations_code_unique" UNIQUE("code")
);

CREATE TABLE "tasks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"property_id" uuid NOT NULL,
	"reservation_id" uuid,
	"type" text NOT NULL,
	"title" text NOT NULL,
	"due_at" timestamp with time zone NOT NULL,
	"assignee_id" uuid,
	"status" text DEFAULT 'todo' NOT NULL,
	"auto_generated" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "units" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"property_id" uuid NOT NULL,
	"name" jsonb NOT NULL,
	"max_guests" integer NOT NULL,
	"bedrooms" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "unlock_events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"pass_id" uuid NOT NULL,
	"lock_device_id" uuid,
	"action" text NOT NULL,
	"result" text NOT NULL,
	"reason" text,
	"ip_hash" text,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "admin_sessions" ADD CONSTRAINT "admin_sessions_admin_id_admin_users_id_fk" FOREIGN KEY ("admin_id") REFERENCES "public"."admin_users"("id") ON DELETE cascade ON UPDATE no action;

ALTER TABLE "conversations" ADD CONSTRAINT "conversations_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE no action ON UPDATE no action;

ALTER TABLE "conversations" ADD CONSTRAINT "conversations_reservation_id_reservations_id_fk" FOREIGN KEY ("reservation_id") REFERENCES "public"."reservations"("id") ON DELETE no action ON UPDATE no action;

ALTER TABLE "conversations" ADD CONSTRAINT "conversations_assignee_id_admin_users_id_fk" FOREIGN KEY ("assignee_id") REFERENCES "public"."admin_users"("id") ON DELETE no action ON UPDATE no action;

ALTER TABLE "guest_access_passes" ADD CONSTRAINT "guest_access_passes_reservation_id_reservations_id_fk" FOREIGN KEY ("reservation_id") REFERENCES "public"."reservations"("id") ON DELETE cascade ON UPDATE no action;

ALTER TABLE "guest_access_passes" ADD CONSTRAINT "guest_access_passes_created_by_admin_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."admin_users"("id") ON DELETE no action ON UPDATE no action;

ALTER TABLE "lock_credentials" ADD CONSTRAINT "lock_credentials_lock_device_id_lock_devices_id_fk" FOREIGN KEY ("lock_device_id") REFERENCES "public"."lock_devices"("id") ON DELETE cascade ON UPDATE no action;

ALTER TABLE "lock_credentials" ADD CONSTRAINT "lock_credentials_reservation_id_reservations_id_fk" FOREIGN KEY ("reservation_id") REFERENCES "public"."reservations"("id") ON DELETE cascade ON UPDATE no action;

ALTER TABLE "lock_devices" ADD CONSTRAINT "lock_devices_property_id_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."properties"("id") ON DELETE cascade ON UPDATE no action;

ALTER TABLE "messages" ADD CONSTRAINT "messages_conversation_id_conversations_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id") ON DELETE cascade ON UPDATE no action;

ALTER TABLE "payments" ADD CONSTRAINT "payments_reservation_id_reservations_id_fk" FOREIGN KEY ("reservation_id") REFERENCES "public"."reservations"("id") ON DELETE no action ON UPDATE no action;

ALTER TABLE "qr_codes" ADD CONSTRAINT "qr_codes_property_id_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."properties"("id") ON DELETE no action ON UPDATE no action;

ALTER TABLE "qr_scans" ADD CONSTRAINT "qr_scans_qr_code_id_qr_codes_id_fk" FOREIGN KEY ("qr_code_id") REFERENCES "public"."qr_codes"("id") ON DELETE cascade ON UPDATE no action;

ALTER TABLE "rate_plans" ADD CONSTRAINT "rate_plans_unit_id_units_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."units"("id") ON DELETE cascade ON UPDATE no action;

ALTER TABLE "reservations" ADD CONSTRAINT "reservations_property_id_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."properties"("id") ON DELETE no action ON UPDATE no action;

ALTER TABLE "reservations" ADD CONSTRAINT "reservations_unit_id_units_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."units"("id") ON DELETE no action ON UPDATE no action;

ALTER TABLE "reservations" ADD CONSTRAINT "reservations_rate_plan_id_rate_plans_id_fk" FOREIGN KEY ("rate_plan_id") REFERENCES "public"."rate_plans"("id") ON DELETE no action ON UPDATE no action;

ALTER TABLE "reservations" ADD CONSTRAINT "reservations_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE no action ON UPDATE no action;

ALTER TABLE "tasks" ADD CONSTRAINT "tasks_property_id_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."properties"("id") ON DELETE no action ON UPDATE no action;

ALTER TABLE "tasks" ADD CONSTRAINT "tasks_reservation_id_reservations_id_fk" FOREIGN KEY ("reservation_id") REFERENCES "public"."reservations"("id") ON DELETE set null ON UPDATE no action;

ALTER TABLE "tasks" ADD CONSTRAINT "tasks_assignee_id_admin_users_id_fk" FOREIGN KEY ("assignee_id") REFERENCES "public"."admin_users"("id") ON DELETE no action ON UPDATE no action;

ALTER TABLE "units" ADD CONSTRAINT "units_property_id_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."properties"("id") ON DELETE cascade ON UPDATE no action;

ALTER TABLE "unlock_events" ADD CONSTRAINT "unlock_events_pass_id_guest_access_passes_id_fk" FOREIGN KEY ("pass_id") REFERENCES "public"."guest_access_passes"("id") ON DELETE cascade ON UPDATE no action;

ALTER TABLE "unlock_events" ADD CONSTRAINT "unlock_events_lock_device_id_lock_devices_id_fk" FOREIGN KEY ("lock_device_id") REFERENCES "public"."lock_devices"("id") ON DELETE no action ON UPDATE no action;

CREATE INDEX "audit_logs_time_idx" ON "audit_logs" USING btree ("occurred_at");

CREATE INDEX "audit_logs_entity_idx" ON "audit_logs" USING btree ("entity_type","entity_id");

CREATE UNIQUE INDEX "guest_access_passes_token_idx" ON "guest_access_passes" USING btree ("token_hash");

CREATE INDEX "reservations_stay_idx" ON "reservations" USING btree ("unit_id","check_in","check_out");

CREATE INDEX "reservations_status_idx" ON "reservations" USING btree ("status");

-- ---------- migration 0001_constraints ----------
-- Constraints Drizzle can't express. Runs on Supabase and on local PGlite.
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- No double booking: two live stays on the same unit may not overlap ([check_in, check_out)).
ALTER TABLE "reservations" ADD CONSTRAINT "reservations_no_overlap"
  EXCLUDE USING gist ("unit_id" WITH =, daterange("check_in", "check_out") WITH &&)
  WHERE ("kind" = 'stay' AND "status" IN ('hold','pending_payment','confirmed','checked_in'));

ALTER TABLE "reservations" ADD CONSTRAINT "reservations_dates_chk"
  CHECK ("kind" <> 'stay' OR ("check_in" IS NOT NULL AND "check_out" > "check_in"));

ALTER TABLE "properties" ADD CONSTRAINT "properties_name_ja_chk" CHECK ("name" ? 'ja');

-- REI-1001, REI-1002, ...
CREATE SEQUENCE IF NOT EXISTS "reservation_code_seq" START 1001;

-- Audit log is append-only.
CREATE OR REPLACE FUNCTION audit_logs_immutable() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'audit_logs is append-only';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER audit_logs_no_update BEFORE UPDATE OR DELETE ON "audit_logs"
  FOR EACH ROW EXECUTE FUNCTION audit_logs_immutable();

-- ---------- migration 0002_booking_payments ----------
CREATE TABLE "rate_overrides" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"rate_plan_id" uuid NOT NULL,
	"date" date NOT NULL,
	"price" integer,
	"closed" boolean DEFAULT false NOT NULL,
	"min_nights" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "refunds" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"payment_id" uuid NOT NULL,
	"stripe_refund_id" text,
	"amount" integer NOT NULL,
	"reason" text,
	"requested_by" uuid,
	"status" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "refunds_stripe_refund_id_unique" UNIQUE("stripe_refund_id")
);

CREATE TABLE "stripe_events" (
	"event_id" text PRIMARY KEY NOT NULL,
	"type" text NOT NULL,
	"payload" jsonb NOT NULL,
	"processed_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "pricing_rules" ALTER COLUMN "target_id" DROP NOT NULL;

ALTER TABLE "reservations" ADD COLUMN "arrival_time" text;

ALTER TABLE "reservations" ADD COLUMN "messaging_id" text;

ALTER TABLE "reservations" ADD COLUMN "guest_note" text;

ALTER TABLE "reservations" ADD COLUMN "cancelled_at" timestamp with time zone;

ALTER TABLE "rate_overrides" ADD CONSTRAINT "rate_overrides_rate_plan_id_rate_plans_id_fk" FOREIGN KEY ("rate_plan_id") REFERENCES "public"."rate_plans"("id") ON DELETE cascade ON UPDATE no action;

ALTER TABLE "refunds" ADD CONSTRAINT "refunds_payment_id_payments_id_fk" FOREIGN KEY ("payment_id") REFERENCES "public"."payments"("id") ON DELETE no action ON UPDATE no action;

CREATE UNIQUE INDEX "rate_overrides_plan_date_idx" ON "rate_overrides" USING btree ("rate_plan_id","date");

-- ---------- migration 0003_site_settings ----------
CREATE TABLE "site_settings" (
	"key" text PRIMARY KEY NOT NULL,
	"value" jsonb NOT NULL,
	"updated_by" uuid,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- ---------- Row Level Security (closed to the public Data API) ----------
ALTER TABLE "admin_sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "admin_users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "audit_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "conversations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "customers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "guest_access_passes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "lock_credentials" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "lock_devices" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "payments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "pricing_rules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "properties" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "qr_codes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "qr_scans" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "rate_plans" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "reservations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tasks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "units" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "unlock_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "rate_overrides" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "refunds" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "stripe_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "site_settings" ENABLE ROW LEVEL SECURITY;

-- ---------- migration bookkeeping ----------
CREATE SCHEMA IF NOT EXISTS "drizzle";
CREATE TABLE IF NOT EXISTS "drizzle"."__drizzle_migrations" (
  id SERIAL PRIMARY KEY,
  hash text NOT NULL,
  created_at bigint
);
INSERT INTO "drizzle"."__drizzle_migrations" ("hash", "created_at") VALUES ('2b83809e441448c1fb0e92f08c052bdbf6e4b225f70268b34eb44815589fc97b', 1789857915988); -- 0000_init
INSERT INTO "drizzle"."__drizzle_migrations" ("hash", "created_at") VALUES ('5a9cf827a338edebce2015e19337e91e81273e10d17ff157f738e3c89801e9a6', 1789857923463); -- 0001_constraints
INSERT INTO "drizzle"."__drizzle_migrations" ("hash", "created_at") VALUES ('e64db015e98b1ca96f2b980da92eb30ba2e0874fb141f62bbf90cb877750467a', 1789862754310); -- 0002_booking_payments
INSERT INTO "drizzle"."__drizzle_migrations" ("hash", "created_at") VALUES ('59fddd7ac8aa0d8fac0a3eefb1a1ab1e6949a3513cea3b121faf5c99b3faf4b0', 1789864251632); -- 0003_site_settings

COMMIT;
