import { and, eq, sql } from "drizzle-orm";
import type { Db } from "../db/client";
import { properties, reservations, tasks } from "../db/schema";
import { zonedToUtc } from "../time";

type PropertyRow = typeof properties.$inferSelect;
type ReservationRow = typeof reservations.$inferSelect;

export async function nextReservationCode(db: Db): Promise<string> {
  const rows = await db.execute(sql`select nextval('reservation_code_seq') as n`);
  const r = (Array.isArray(rows) ? rows[0] : (rows as { rows: { n: string }[] }).rows[0]) as { n: string | number };
  return `REI-${r.n}`;
}

/** Guest-facing validity window: check-in date @ check-in time → check-out date @ check-out time (property TZ). */
export function stayWindow(p: Pick<PropertyRow, "timezone" | "checkInTime" | "checkOutTime">, checkIn: string, checkOut: string) {
  return {
    from: zonedToUtc(checkIn, p.checkInTime, p.timezone),
    until: zonedToUtc(checkOut, p.checkOutTime, p.timezone),
  };
}

/**
 * Checkout-day cleaning task, created when a stay is confirmed and moved when
 * dates change. Idempotent: one auto cleaning task per reservation.
 */
export async function syncCheckoutTask(db: Db, r: ReservationRow, p: PropertyRow, name: string) {
  if (r.kind !== "stay" || !r.checkOut) return;
  const due = zonedToUtc(r.checkOut, p.checkOutTime, p.timezone);
  const existing = await db
    .select()
    .from(tasks)
    .where(and(eq(tasks.reservationId, r.id), eq(tasks.autoGenerated, true), eq(tasks.type, "cleaning")));
  const title = `清掃・リネン交換：${name}（${r.code} チェックアウト後）`;
  if (r.status === "cancelled") {
    for (const t of existing) if (t.status === "todo") await db.delete(tasks).where(eq(tasks.id, t.id));
    return;
  }
  if (existing[0]) {
    await db.update(tasks).set({ dueAt: due, title }).where(eq(tasks.id, existing[0].id));
  } else {
    await db.insert(tasks).values({
      propertyId: p.id,
      reservationId: r.id,
      type: "cleaning",
      title,
      dueAt: due,
      autoGenerated: true,
    });
  }
}
