-- =====================================================================
-- REIMI platform — upgrade 0002_booking_payments (run once, only if your project was set up before this file existed)
-- Generated by scripts/gen-supabase-sql.mjs. Paste into Supabase → SQL Editor → Run.
-- =====================================================================
BEGIN;

-- Skips itself if this migration was already applied.
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM "drizzle"."__drizzle_migrations" WHERE created_at = 1789862754310) THEN
    RAISE EXCEPTION 'already applied: 0002_booking_payments';
  END IF;
END $$;

CREATE TABLE "rate_overrides" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"rate_plan_id" uuid NOT NULL,
	"date" date NOT NULL,
	"price" integer,
	"closed" boolean DEFAULT false NOT NULL,
	"min_nights" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "refunds" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"payment_id" uuid NOT NULL,
	"stripe_refund_id" text,
	"amount" integer NOT NULL,
	"reason" text,
	"requested_by" uuid,
	"status" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "refunds_stripe_refund_id_unique" UNIQUE("stripe_refund_id")
);

CREATE TABLE "stripe_events" (
	"event_id" text PRIMARY KEY NOT NULL,
	"type" text NOT NULL,
	"payload" jsonb NOT NULL,
	"processed_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "pricing_rules" ALTER COLUMN "target_id" DROP NOT NULL;

ALTER TABLE "reservations" ADD COLUMN "arrival_time" text;

ALTER TABLE "reservations" ADD COLUMN "messaging_id" text;

ALTER TABLE "reservations" ADD COLUMN "guest_note" text;

ALTER TABLE "reservations" ADD COLUMN "cancelled_at" timestamp with time zone;

ALTER TABLE "rate_overrides" ADD CONSTRAINT "rate_overrides_rate_plan_id_rate_plans_id_fk" FOREIGN KEY ("rate_plan_id") REFERENCES "public"."rate_plans"("id") ON DELETE cascade ON UPDATE no action;

ALTER TABLE "refunds" ADD CONSTRAINT "refunds_payment_id_payments_id_fk" FOREIGN KEY ("payment_id") REFERENCES "public"."payments"("id") ON DELETE no action ON UPDATE no action;

CREATE UNIQUE INDEX "rate_overrides_plan_date_idx" ON "rate_overrides" USING btree ("rate_plan_id","date");

ALTER TABLE "rate_overrides" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "refunds" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "stripe_events" ENABLE ROW LEVEL SECURITY;

INSERT INTO "drizzle"."__drizzle_migrations" ("hash", "created_at") VALUES ('e64db015e98b1ca96f2b980da92eb30ba2e0874fb141f62bbf90cb877750467a', 1789862754310); -- 0002_booking_payments

COMMIT;
