-- =====================================================================
-- REIMI platform — upgrade 0003_site_settings (run once, only if your project was set up before this file existed)
-- Generated by scripts/gen-supabase-sql.mjs. Paste into Supabase → SQL Editor → Run.
-- =====================================================================
BEGIN;

-- Skips itself if this migration was already applied.
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM "drizzle"."__drizzle_migrations" WHERE created_at = 1789864251632) THEN
    RAISE EXCEPTION 'already applied: 0003_site_settings';
  END IF;
END $$;

CREATE TABLE "site_settings" (
	"key" text PRIMARY KEY NOT NULL,
	"value" jsonb NOT NULL,
	"updated_by" uuid,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "site_settings" ENABLE ROW LEVEL SECURITY;

INSERT INTO "drizzle"."__drizzle_migrations" ("hash", "created_at") VALUES ('59fddd7ac8aa0d8fac0a3eefb1a1ab1e6949a3513cea3b121faf5c99b3faf4b0', 1789864251632); -- 0003_site_settings

COMMIT;
