import Link from "next/link";
import { requireAdmin } from "@/server/auth/session";
import { can } from "@/server/auth/permissions";
import { listTasks } from "@/server/modules/queries";
import { PageTitle, When, loc } from "@/components/admin/ui";
import { TaskStatusButtons } from "@/components/admin/client";

export const dynamic = "force-dynamic";

const COLS: [string, string, string][] = [
  ["todo", "未着手", "border-t-amber-400"],
  ["doing", "作業中", "border-t-[#146cd6]"],
  ["done", "完了", "border-t-emerald-500"],
];

export default async function TasksPage() {
  const me = await requireAdmin("tasks");
  const rows = await listTasks();
  const canEdit = can(me, "tasks");
  return (
    <>
      <PageTitle title="タスクボード" sub="予約が確定すると、チェックアウト時刻に清掃タスクが自動で作られます。日程変更・キャンセルにも追従します。" />
      <div className="grid gap-4 lg:grid-cols-3">
        {COLS.map(([k, label, border]) => {
          const items = rows.filter((x) => x.t.status === k).slice(0, k === "done" ? 6 : 50);
          return (
            <section key={k} className={`rounded-2xl border border-t-4 border-line/80 bg-panel ${border}`}>
              <header className="flex items-center justify-between px-4 py-3">
                <h2 className="text-sm font-bold text-ink">{label}</h2>
                <span className="rounded-full bg-surface px-2 py-0.5 text-xs font-bold text-muted">{rows.filter((x) => x.t.status === k).length}</span>
              </header>
              <ul className="space-y-2 px-3 pb-3">
                {items.map(({ t, p, r, a }) => (
                  <li key={t.id} className="rounded-xl border border-line/70 bg-surface/60 p-3">
                    <div className="flex items-start justify-between gap-2">
                      <p className="text-sm font-semibold text-ink">{t.title}</p>
                      {t.autoGenerated && <span className="shrink-0 rounded bg-[#f7c948]/30 px-1.5 py-0.5 text-[10px] font-bold text-amber-900">自動</span>}
                    </div>
                    <p className="mt-1 text-xs text-muted">{loc(p.name)}{r && <> · <Link href={`/admin/reservations/${r.code}`} className="text-brand">{r.code}</Link></>}</p>
                    <div className="mt-2 flex items-center justify-between text-xs">
                      <span className="text-muted">期限 <When at={t.dueAt} tz={me.timezone} compact /> · {a?.name ?? "未割当"}</span>
                      <TaskStatusButtons id={t.id} status={t.status} canEdit={canEdit} />
                    </div>
                  </li>
                ))}
              </ul>
            </section>
          );
        })}
      </div>
    </>
  );
}
